### PR TITLE
Change Brief Card font-size on string length

### PR DESCRIPTION
**Pull request by revett**
### Problem

Truncated strings look crap.

### Solution

Decrease the size of the string if it is over a given amount of letters.

### CODE REVIEW

**Comment by revett** [comment]
@benjdlambert 

- what do you think of this solution?
- how can I share this function with three presentational components?

Thanks! ⛱

**Comment by revett** [comment]
[[CR] Change text size based on length of string](https://trello.com/c/j7Y3VOnf/768-cr-change-text-size-based-on-length-of-string)

**Comment by benjdlambert** [comment]
So I mean, you could extract this out into a file called `shared/lib/font-size.js`

```js
//font-size.js
export default function(text) {
    if (text.length) > ...
}
```
Then use it like so:

```js
import fontsize from '../shared/lib/font-size'
import classnames from 'classnames';

const classes = classnames({
    active: true,
    [fontsize(mytext)] : true
})

//or

const classes = classnames(
   fontsize(mytext), { 
   active: true
})
```

**Comment by revett** [comment]
@benjdlambert this is ready for a re-review! 💥

**Pull request closed without merging**
