### PR TITLE
Yarn 🐈

### PR DESCRIPTION
**Pull request by revett**
### Problem

1. npm sucks.
1. We aren't keeping up with the cool kids, and thus may turn into Maslen.

### Solution

Start using [Yarn](https://github.com/yarnpkg/yarn) 🎉

### Notes

- Only commiting the `.lock` file so still able to use both methods to install.

### CODE REVIEW

**Comment by revett** [comment]
[[SA] Yarn 🐈](https://trello.com/c/tWkYUJo8/702-sa-yarn)

**Comment by revett** [comment]
@benjdlambert you can review as well 😃

**Comment by revett** [comment]
@vidsy/tech review please 👌

**Comment by benjdlambert** [comment]
Stupid thing. I thought I'd clicked approve.

**Comment by revett** [comment]
@benjdlambert thanks 😂

**Pull request merged**
