### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by kdankov**
**Problem**
File path was too complicated and some files are missing

**Solution**
Simplify the file paths and add missing files

### CODE REVIEW

**Comment by revett** [comment]
I wouldn't commit the **bower components** to Github, they can be ignored.

**Comment by revett** [comment]
@kdankov can we also remove some of the files in `fonts/` ? Are they all used?

**Comment by revett** [comment]
@kdankov let's leave JS for another PR :) as we are doing quite a few changes over the next few days

**Comment by kdankov** [comment]
Removed the bower components and ignored the path.

For the fonts - different font files are used for different browsers. We possibly delete 2 css files but it is useful for reference. Let me know if that is ok.

**Comment by revett** [comment]
🍰

**Comment by revett** [comment]
Nice work!

**Pull request merged**
