### PR TITLE
Fix Image URL

### PR DESCRIPTION
**Pull request by benjdlambert**
### Problem
- The responsive image to tell you to GTFO mobile had the wrong path.

### Solution
- Update the path!

### Notes
@revett @stevenjack 

Managed to get everything running and working locally with `docker-compose up` in this directory.
I think I had some weird caching behaviour of the images tagged `:latest` locally, don't you if you're seeing the same @revett or seen something like this before? I think its because it doesn't revalidate `:latest`?

Wiped all my images and `docker-compose up` worked a treat.

screen shot 2016-08-17 at 03 45 15

We could also probably looking at waiting to start the `gulp` container, after the `node-builder` container has started using something like `docker-wait` or something.

### CODE REVIEW

**Comment by benjdlambert** [comment]
WAIT! HOLD THE PHONE. I've worked it out. ☎️

**Comment by revett** [comment]
@benjdlambert nice!

**Comment by revett** [comment]
@benjdlambert Is this ready to merge?

**Comment by benjdlambert** [comment]
👍

**Pull request merged**
