### PR TITLE
Added Collectives and Rework Validation 📒

### PR DESCRIPTION
**Pull request by benjdlambert**
### Problem
- Need to move across the old layout
- This means we need collectives
- Because of the small components, validation is all over the place

### Solution
- Port across the collectives
- Checkbox niceness!
- Rework the validation, so component errors are passed in by a higher-order component
- Fix the validation between sections
- Fix the avatar issues
- Add styles for the image errors
- Added more validation for email and urls

gid

### Notes
https://trello.com/c/zlxcc8Fq/299-cr-rewrite-existing-js-to-jsx
@revett @stevenjack

### CODE REVIEW

**Comment by benjdlambert** [comment]
It trims the video, but check it out, it does work.

**Comment by revett** [comment]
Like the GIF and amount of commits!

**Comment by revett** [comment]
Looking now 👀

**Comment by revett** [comment]
Start @ Wizard

**Comment by revett** [comment]
Then look at validation components

**Comment by revett** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;o4ogciWA&#x2F;300-cr-add-in-new-jsx-features-for-onboarding"> [CR] Add in new JSX features for onboarding</a>

**Comment by revett** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zlxcc8Fq&#x2F;299-cr-rewrite-existing-js-to-jsx"> [CR] Rewrite existing JS to JSX</a>

**Comment by revett** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;J7lmLza2&#x2F;298-cr-port-html-across-to-react"> [CR] Port HTML across to React</a>

**Comment by revett** [comment]
🍰 

**Awesome** work 😄 I think we'll need some copy changes for the error messages, but they can be done later on

**Pull request merged**
